### ISSUE TITLE
to-do issue megathread

### ISSUE THREAD

**Issue by robingall2910** [robingall2910/RobTheBoat#17]
Any comments below would be seperated suggestions, bug fixes, and etc that I have planned and/or planning to do.

**Comment by robingall2910** [comment]
allow the config command to bypass if you're either bot developer or owner // pending

**Comment by robingall2910** [comment]
_still_ fix the .play exception issue // not done

**Comment by robingall2910** [comment]
fix the youtube-dl download corruption, I tried by delaying the downloading process, but Seth says it's streaming so idk // not done

**Comment by robingall2910** [comment]
rewrite/update for the d.py rewrite // pending

**Comment by robingall2910** [comment]
suggestions:

catch the coins with >coin and collect them to buy something (who knows what I can do)

social system?

**Comment by robingall2910** [comment]
extras:

possibly remove porn completely, im not really tempted to but it's an idea

remove myanimelist, im not registering again

**Comment by robingall2910** [comment]
also another one, but this is for all the bots in the ``Gears of Bots`` Discord guild:

add a channel where bots report if there's a shard down or crashed, this includes Some Dragon, Napstabot, and probably Ruby Rose. This could also be added to bots without shards, and report something before they crash of some sort.

**Comment by Maxie01** [comment]
I like the above idea idea. I'll make this a planed feature for Napstabot.

**Comment by robingall2910** [comment]
possibility to add speeds, ex 1.25, 1.50, 1.75, 2.00 just like how the video speed config is in the youtube website // not done

**Comment by CreeperSeth** [comment]
nither is this gonna happen

**Comment by robingall2910** [comment]
most of these things were done anyway @CreeperSeth well er the bugs
