### ISSUE TITLE
ability to restart automatically right after a crash.

### ISSUE THREAD

**Issue by robingall2910** [robingall2910/RobTheBoat#19]
this is gonna be something related to linux since the process will die off, and it's not gonna restart via python...

**Comment by Adaptified** [comment]
I did it in a batch file

**Comment by robingall2910** [comment]
update: bot crashes and the startup command doesn't work. this issue also affects Ruby Rose, although it has a boot loop command and I don't. Either way, same effect.

**Comment by robingall2910** [comment]
It's been done, after a few months.
