### ISSUE TITLE
press f issue

### ISSUE THREAD

**Issue by Maxie01** [robingall2910/RobTheBoat#23]
Press F command displays incorrect numbers

![picture](https://catch-me-outside.how-about-th.at/afcdb8.png)
![picture2](https://catch-me-outside.how-about-th.at/76f92b.png)

you should uh, fix it :3

**Comment by EJH2** [comment]
https://github.com/robingall2910/RobTheBoat/blob/cd3db473293e4346e390d82c744404754f4fcdae/commands/fuckery.py#L50 Can confirm, needs fixing :3

**Comment by Maxie01** [comment]
never mind

**Comment by robingall2910** [comment]
you guys just got memed

**Comment by master98ofu** [comment]
kekekek
